name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t gitrepo .
        echo ${{ secrets.GCP_KEY_FILE }} | base64 -d > key.json
        docker login -u _json_key --password-stdin https://gcr.io < key.json
        docker tag gitrepo gcr.io/github2405/gitrepo:v3
        docker push gcr.io/github2405/gitrepo:v3

    - name: Deploy to GKE
      run: |
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project <project-id>
        gcloud container clusters get-credentials mycluster24 --zone us-central1
        kubectl apply -f deployment.yaml -f service.yaml

